### ISSUE TITLE
Poor Code Quality

### ISSUE THREAD

**Issue by Zamazenta** [SurvirvorHRG/Horion#28]
This code is kinda ugly... Why would you write this????

One thing that needs improvement is naming. Instead of blindly pasting out of ida and ending up with sub_blah, actually give it a name that makes sense. We don't like v1 v2 v3 v4 and v5 variables either as those are also blindly pasted from ida. Give them proper names. By the way "idk" isn't a good variable name either.

Even after giving everything proper names, there is still tons that could be improved on.
 
Comparing this code to hat code is like comparing a filthy homeless peasant (horion) to a rich king living in a giant castle (hat).

Please improve the code quality.

**Comment by Godsoft029** [comment]
agreed

**Comment by Godsoft029** [comment]
send links to bad code and we'll improve it

**Comment by Godsoft029** [comment]
closing the issue until we get further info
