### ISSUE TITLE
Cannot compile Horion in 2019 vs

### ISSUE THREAD

**Issue by hYdos** [SurvirvorHRG/Horion#35]
i have downloaded your code and opened the solution. i press the start button on release and on x64 and everything stops responding. any ideas on why and how to fix this?

**Comment by hYdos** [comment]
also i have tried building the solution. this is what i get `1>------ Build started: Project: Horion, Configuration: Debug x64 ------
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by BrandonioR** [comment]
You know no one can help you without the build log lmfao if you dont know how to debug stop messing with the source

**Comment by hYdos** [comment]
well, how am i ment to debug with the program which crashes?

**Comment by hYdos** [comment]
also what i uploaded is the build log
its nothing but that

**Comment by hYdos** [comment]
ok got a fix C:\Users\hayde\Desktop\dev\Horion\Horion.vcxproj : warning  : The build tools for v142 cannot be found. Install v142 to build using the v142 build tools.

C:\Users\hayde\Desktop\dev\Horion\Horion.vcxproj : warning  : Platform 'Win32' referenced in the project file 'Horion' cannot be found.

C:\Users\hayde\Desktop\dev\Horion\Horion.vcxproj : warning  : Platform 'x64' referenced in the project file 'Horion' cannot be found.
install that stuff

**Comment by Godsoft029** [comment]
you might consider properly installing visual studio first before trying to compile anything
