### ISSUE TITLE
VS 2019 Ambiguous Symbol Issues

### ISSUE THREAD

**Issue by BrandonioR** [SurvirvorHRG/Horion#36]
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\transact.h(139,10): error C2872:  'byte': ambiguous symbol
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared\rpcndr.h(191,23): message :  could be 'unsigned char byte'

Tried all development kits and seems to be an issue with the codes compatibility for vs2019

**Comment by Godsoft029** [comment]
Checked the file on my local setup and it was already set to unsigned char. Reopen if you find similar issues

**Comment by BrandonioR** [comment]
> Checked the file on my local setup and it was already set to unsigned char. Reopen if you find similar issues

oh and just one thing, all variable have retarded names can you consider cleaning up the code abit?

**Comment by Godsoft029** [comment]
would help if you could give us examples of bad code

**Comment by zacian-source** [comment]
> would help if you could give us examples of bad code


`DWORD WINAPI analyticsThread(LPVOID lpParam) {
	logF("Analytics started");
	__try {
		auto sendRequest = [](char* request) {
			wchar_t boi[200];
			swprintf_s(boi, 200, L"https://hbob.ml/horion/action.php?type=%S", request);
			WinHttpClient client(boi);`

dont define as boi and give proper variable names i suppose also: 

	__except (EXCEPTION_EXECUTE_HANDLER) {
#ifdef _DEBUG
		logF("got some wierd error idk");
		__debugbreak();
#else

maybe proper feedback?

**Comment by richardletshacks** [comment]
@Godsoft029 always defines variables as boi when doesnt want to think of any name 😬

**Comment by zacian-source** [comment]
lmao

**Comment by Godsoft029** [comment]
can confirm

**Comment by Godsoft029** [comment]
> __except (EXCEPTION_EXECUTE_HANDLER) {
#ifdef _DEBUG
logF("got some wierd error idk");
__debugbreak();
#else

We actually never got this to happen, made for some people who reported crashes after we added the analytics.

**Comment by Godsoft029** [comment]
f8df580 has fixed the original issue
